import type { Locale } from './i18n';

export const aboutStory: Record<Locale, string[]> = {
  en: [
    'Every movement begins with a story. The story behind EnnobleRise Global Trust begins not in a boardroom but in a childhood shaped by conflict, resilience, and an unwavering belief in the dignity of the human spirit.',
    "Dr. Kasthuri Henry's life journey, chronicled in her international bestselling book Ennobled for Success: From Civil War to a US CFO, traces a path from adversity to global leadership. Her experiences revealed a powerful truth: the greatest transformation begins not with wealth or power, but with the ennobling of the human spirit.",
    'Throughout her career as a financial strategist, professor, and corporate executive, Dr. Henry helped lead complex transformations across industries — from global business initiatives to public sector institutions. Yet the most profound lessons did not come from spreadsheets or board meetings. They came from people: teachers who shaped young minds, women who carried families through hardship, and youth whose potential waited only for opportunity.',
    'Over time, a pattern became unmistakable. When youth are ennobled with confidence, when educators are strengthened as architects of human potential, and when women gain the tools for economic and social leadership — communities transform.',
    'As the world enters an era increasingly shaped by artificial intelligence, Dr. Henry believes the defining question of our time is not technological capability; it is human stewardship. The future will be determined by leaders who combine emotional intelligence, financial resilience, and mindful leadership with cultural, generational, and gender intelligence.',
    'From that conviction, EnnobleRise Global Trust was born. Its mission is simple yet profound: to cultivate a generation of compassionate leaders by ennobling youth, educators, and women with the tools to transform their lives and communities. Because when the human spirit is ennobled, transformation does not stop with one individual. It ripples across families, communities, and generations — and that ripple has the inherent power to change the world.',
  ],
  fr: [
    "Chaque mouvement commence par une histoire. Celle d'EnnobleRise Global Trust ne commence pas dans une salle de conseil, mais dans une enfance marquée par le conflit, la résilience et une foi inébranlable en la dignité de l'esprit humain.",
    "Le parcours de la Dre Kasthuri Henry, retracé dans son best-seller international Ennobled for Success: From Civil War to a US CFO, mène de l'adversité au leadership mondial. Son expérience a révélé une vérité puissante : la plus grande transformation ne commence pas par la richesse ou le pouvoir, mais par l'ennoblissement de l'esprit humain.",
    "Tout au long de sa carrière de stratège financière, de professeure et de dirigeante d'entreprise, la Dre Henry a conduit des transformations complexes, des initiatives mondiales aux institutions publiques. Mais les leçons les plus profondes ne sont pas venues des tableurs ni des conseils d'administration. Elles sont venues des personnes : des enseignants qui forment les jeunes esprits, des femmes qui portent leur famille dans l'épreuve, et des jeunes dont le potentiel n'attendait qu'une opportunité.",
    "Avec le temps, un schéma est devenu évident. Quand les jeunes sont ennoblis par la confiance, quand les éducateurs sont renforcés comme architectes du potentiel humain, et quand les femmes obtiennent les outils du leadership économique et social — les communautés se transforment.",
    "Alors que le monde entre dans une ère façonnée par l'intelligence artificielle, la Dre Henry croit que la question décisive de notre temps n'est pas la capacité technologique, mais l'intendance humaine. L'avenir appartiendra aux leaders qui allient intelligence émotionnelle, résilience financière et leadership conscient à l'intelligence culturelle, générationnelle et de genre.",
    "De cette conviction est né EnnobleRise Global Trust. Sa mission est simple et profonde : cultiver une génération de leaders compatissants en ennoblissant les jeunes, les éducateurs et les femmes avec les outils pour transformer leur vie et leur communauté. Car lorsque l'esprit humain est ennobli, la transformation ne s'arrête pas à une personne. Elle se propage aux familles, aux communautés et aux générations — et cette onde porte en elle le pouvoir de changer le monde.",
  ],
  es: [
    'Todo movimiento comienza con una historia. La de EnnobleRise Global Trust no comienza en una sala de juntas, sino en una infancia marcada por el conflicto, la resiliencia y una fe inquebrantable en la dignidad del espíritu humano.',
    'El camino de la Dra. Kasthuri Henry, narrado en su bestseller internacional Ennobled for Success: From Civil War to a US CFO, va de la adversidad al liderazgo global. Su experiencia reveló una verdad poderosa: la mayor transformación no comienza con riqueza o poder, sino con el ennoblecimiento del espíritu humano.',
    'A lo largo de su carrera como estratega financiera, profesora y ejecutiva corporativa, la Dra. Henry condujo transformaciones complejas, desde iniciativas empresariales globales hasta instituciones públicas. Pero las lecciones más profundas no vinieron de hojas de cálculo ni juntas directivas. Vinieron de las personas: maestros que forman mentes jóvenes, mujeres que sostienen familias en la adversidad y jóvenes cuyo potencial solo esperaba una oportunidad.',
    'Con el tiempo, un patrón se volvió inconfundible. Cuando los jóvenes son ennoblecidos con confianza, cuando los educadores son fortalecidos como arquitectos del potencial humano, y cuando las mujeres obtienen las herramientas del liderazgo económico y social — las comunidades se transforman.',
    'Mientras el mundo entra en una era moldeada por la inteligencia artificial, la Dra. Henry cree que la pregunta decisiva de nuestro tiempo no es la capacidad tecnológica, sino la responsabilidad humana. El futuro lo definirán líderes que combinen inteligencia emocional, resiliencia financiera y liderazgo consciente con inteligencia cultural, generacional y de género.',
    'De esa convicción nació EnnobleRise Global Trust. Su misión es simple y profunda: cultivar una generación de líderes compasivos ennobleciendo a jóvenes, educadores y mujeres con las herramientas para transformar sus vidas y comunidades. Porque cuando el espíritu humano es ennoblecido, la transformación no se detiene en una persona. Se propaga a familias, comunidades y generaciones — y esa onda lleva en sí el poder de cambiar el mundo.',
  ],
};
